export const MAPS_API_KEY = "AIzaSyB6QpKDK6ELMsg6Vx57P0inHtHJ_KeSIFc"

export const Actions = {
    CONCAT_POSTS:"CONCAT_POSTS",
    ADD_POST:"ADD_POST",
    UPDATE_POST:"UPDATE_POST",
    SET_POSTS:"SET_POSTS",
    APPEND_POSTS:"APPEND_POSTS",
    SWITCH_ITERACTION_MODE:"SWITCH_MODE",
    SET_ITERACTION_MODE:"SET_ITERACTION_MODE",
    INITIALIZE_POSTS_CREATION:"INITIALIZE_POSTS_CREATION",
    CLEAR_POST_CREATION: "CLEAR_POST_CREATION",
    INSERT_DATA_TO_POST: "INSERT_DATA_TO_POST",
    CREATE_RELATIONSHIP:"CREATE_RELATIONSHIP"

}


export const InteractionTypes = {
    EDIT_MODE:"ED",
    VIEW_MODE:"VM"
}